// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rjiozocqwhpocvhxncmd.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqaW96b2Nxd2hwb2N2aHhuY21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0MTk0MTQsImV4cCI6MjA0Nzk5NTQxNH0.FLzD_Sb6EMZ9oZsgF76YQkh4XktadYgLUCpe-D31s7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);